name: Build and Deploy to Sandbox

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '.maven/**'
      
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '.maven/**'
      
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.6
    
    # MUNIT RUN (PR)
    - name: Run MUnit Tests (PR only)
      if: github.event_name == 'pull_request'
      run: |
        MAVEN_OPTS="--add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED" \
        mvn -B clean test -s .maven/settings.xml

    # BUILD (PUSH)
    - name: Build with Maven (Skip tests on push)
      if: github.event_name == 'push'
      run: |
        MAVEN_OPTS="--add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED" \
        mvn -B clean package -DskipTests -s .maven/settings.xml

    - name: Build with Maven
      run: mvn -B clean package -s .maven/settings.xml

    - name: Stamp artifact file name with commit hash
      if: github.event_name == 'push'   # only needed for deploy flow
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2

    - name: Upload artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: target/*.jar


  upload:
    needs: build
    if: github.event_name == 'push'   # ONLY after merge
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - uses: actions/download-artifact@v4
      with:
        name: artifacts

    - name: Upload to Exchange
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy \
         -s .maven/settings.xml \
         -Dmule.artifact=$artifactName


  deploy:
    needs: upload
    if: github.event_name == 'push'   # ONLY after merge
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - uses: actions/download-artifact@v4
      with:
        name: artifacts

    - name: Deploy to Sandbox
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -s .maven/settings.xml \
         -DskipTests \
         -DskipDeploymentVerification="true"